### PR TITLE
i believe it must be method call here :)

### PR DESCRIPTION
**Pull request by Vasiliy-Bondarenko**
tested in my app like this:
```
    /** @test */
    public function get_all()
    {
        // given
        $user = $this->user;

        // action
        $user->addMeta('key', 'value');
        $user->addMeta('other', 'another_value');

        // assert
        $user = $user->fresh();
        $this->assertEquals(
            ['key' => 'value', 'other' => 'another_value'],
            $user->getAllMeta()->toArray()
        );
    }
```

### CODE REVIEW

**Comment by chrismichaels84** [comment]
It's been a long time since I've actually used this package, but looking at https://laravel.com/docs/5.4/eloquent-relationships#eager-loading tells me that a property is fine here.

Is it throwing an error or not working as expected?

**Comment by Vasiliy-Bondarenko** [comment]
Throwing "Call to a member function pluck() on null"
http://joxi.ru/LmG4Dv7iQ6dJ2l?d=1
When changed to method call - test passes.

**Comment by chrismichaels84** [comment]
Interesting. I don't see how that would have changed, but that looks good to me. Merging and releasing.

**Comment by Vasiliy-Bondarenko** [comment]
Thanks.

One more question...
Did you intentionally made it possible to create multiple metas with the same key?
It does not make much sense to me... Why?
```
        $user->addMeta('key', 1);
        $user->addMeta('key', 2);
```
It really creates multiple rows in DB with the same type, id and key.

**Pull request merged**
